### ISSUE TITLE
Redesign of their website

### ISSUE THREAD

**Issue by flowdee** [flowdee/ohdear#12]
We must apply the redesign to the plugin by switching the logo/icon and also to the WP org header + logo graphics

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/2011930895/50566/

**Comment by liquiem** [comment]
![oh-dear-logo](https://user-images.githubusercontent.com/7579306/193751648-425d66d2-5aa6-4615-9066-9e2741b1135d.jpg)
![oh-dear-og-image](https://user-images.githubusercontent.com/7579306/193751653-45ff488a-95d3-42fa-9483-8347d5f37c13.jpg)
![oh-dear-twitter-banner-dark](https://user-images.githubusercontent.com/7579306/193751659-74b98090-a418-4b4b-8861-bd754abc662e.jpg)

**Comment by liquiem** [comment]
@webdj-agency 

here the required sizes. Have fun.


![banner-772x250](https://user-images.githubusercontent.com/7579306/197701450-cadc3a44-a749-4f8a-9d88-92fdee68277e.png)
![banner-1544x500](https://user-images.githubusercontent.com/7579306/197701455-b737cb20-881f-41e1-bf32-720659ac74bd.png)
![icon-128x128](https://user-images.githubusercontent.com/7579306/197701460-7f7f6d6d-1ed9-4763-9584-d8b0fd380834.png)
![icon-256x256](https://user-images.githubusercontent.com/7579306/197701462-d4ad8ea4-d41e-4be4-96df-fcd05ae8a560.png)

**Comment by liquiem** [comment]
@flowdee i donno have the rights to assign tickets in this space. Please grant! This ticket should be assigned to WebDJ

**Comment by webdj-agency** [comment]
@liquiem i downloaded 4 last images. the icon has size: 127px * 128px. but it must be 128px * 128px. it is a standard. otherwise the icon properties (уюпю sharpness, focus) can look blurred at retina screens.
all other images size is fine. please provide the 128*128 icon

**Comment by flowdee** [comment]
FYI @liquiem

**Comment by liquiem** [comment]
![icon-128x128](https://user-images.githubusercontent.com/7579306/199490917-f1d0aadd-750e-43b1-8659-d9e2a2bbe2d4.png)

how could that happen??? 


@webdj-agency fixed version
