### ISSUE TITLE
Release 1.0.2

### ISSUE THREAD

**Issue by flowdee** [flowdee/ohdear#14]
Could you please prepare & release version 1.0.2?

- [x] Update version number in main plugin file + readme.txt
- [x] readme.txt: Tested up to & stable tag
- [x] readme.txt: Changelog
- [x] Push to master
- [x] Create and push tag 1.0.2
- [x] Check if auto-deploy to wporg went through properly

**Comment by webdj-agency** [comment]
Done: https://wordpress.org/plugins/ohdear/

**Comment by flowdee** [comment]
Released with v1.0.2
